### PR TITLE
Add spacing to section headers in terminal output

### PR DESCRIPTION
**Pull request by vritant24**
In vscodeedu, pedal's output looks like so:
image

Added spacing to section headers to improve the highlighting.

If this change looks ok to take, I will need your help @acbart to create published package we can consume.

### CODE REVIEW

**Comment by acbart** [comment]
Looks good, I merged it in. I can trigger a new release on Pypi in just a bit. Once we have #22 this will be much easier. There'll be time this summer, I think.

**Comment by vritant24** [comment]
> Looks good, I merged it in. I can trigger a new release on Pypi in just a bit. Once we have #22 this will be much easier. There'll be time this summer, I think.

Thanks so much for the quick response! Also for fixing the tests!

**Comment by acbart** [comment]
Version 2.6.2 was just pushed to PyPi, hopefully everything works as you need! There were some other minor changes added back around SIGCSE (March), so if you haven't pulled since then, there might be some other new things. I wouldn't expect things to break, but let me know if there are any issues!

**Comment by vritant24** [comment]
> Version 2.6.2 was just pushed to PyPi, hopefully everything works as you need! There were some other minor changes added back around SIGCSE (March), so if you haven't pulled since then, there might be some other new things. I wouldn't expect things to break, but let me know if there are any issues!

Tested it out in our PPE environment and it looks good! Thanks again for the quick turnaround

**Pull request merged**
